//SUBJECTS - QUIZ - QUESTIONS - ANSWERS
export const GET_QUIZ = 'GET_QUIZ';
export const GET_QUIZZES = 'GET_QUIZZES';
export const SAVE_ANSWER = 'SAVE_ANSWER'; 
export const ADD_SCORE = 'ADD_SCORE'; //MOVE TO SCORE
export const GET_SUBJECTS = 'GET_SUBJECTS'; //MOVE TO SUBJECT
export const TOP_QUIZZES_BY_SUBJECT = 'TOP_QUIZZES_BY_SUBJECT'
export const TOP_QUIZZES_BY_LEVEL = 'TOP_QUIZZES_BY_LEVEL'
export const TOP_QUIZZES_BY_USER = 'TOP_QUIZZES_BY_USER'
export const QUIZZES_COUNT = 'QUIZZES_COUNT'
export const QUIZZES_SUM_PLAYED = 'QUIZZES_SUM_PLAYED'
export const QUESTIONS_COUNT = 'QUESTIONS_COUNT'
export const GET_SUBJECT = 'GET_SUBJECT'
export const SUGGEST_QUIZZES = 'SUGGEST_QUIZZES'
export const RESET_CHOICES = 'RESET_CHOICES'
export const SUBJECTS_ON = 'SUBJECTS_ON'


//SCORE
export const LAST_THREE_WINNERS = 'LAST_THREE_WINNERS'
export const GET_WINNERS = 'GET_WINNERS'
export const CHECK_WINNER = 'CHECK_WINNER'

export const TOP_SCHOOLS_BY_SCORE = 'TOP_SCHOOLS_BY_SCORE'
export const TOP_SCHOOLS_BY_MEDALS = 'TOP_SCHOOLS_BY_MEDALS'
export const TOP_SCHOOLS_THIS_WEEK = 'TOP_SCHOOLS_THIS_WEEK'
export const TOP_SCHOOLS_BY_LEVEL = 'TOP_SCHOOLS_BY_LEVEL'
export const TOP_SCHOOLS_BY_SUBJECT = 'TOP_SCHOOLS_BY_SUBJECT'

export const TOP_USERS_BY_SCORE = 'TOP_USERS_BY_SCORE'
export const TOP_USERS_BY_MEDALS = 'TOP_USERS_BY_MEDALS'
export const TOP_USERS_THIS_WEEK = 'TOP_USERS_THIS_WEEK'
export const TOP_USERS_BY_LEVEL = 'TOP_USERS_BY_LEVEL'
export const TOP_USERS_BY_SUBJECT = 'TOP_USERS_BY_SUBJECT'

export const USER_COUNT_SCORE = 'USER_COUNT_SCORE'
export const USER_SUM_SCORE = 'USER_SUM_SCORE'
export const USER_SUM_MEDALS = 'USER_SUM_MEDALS'
export const USER_AVERAGE = 'USER_AVERAGE'
export const USER_FAVORITE = 'USER_FAVORITE'

export const POPULAR_SUBJECTS = 'POPULAR_SUBJECTS'



//USER
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_USER = 'GET_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const NEWEST_USER = 'NEWEST_USER'
export const USERS_COUNT = 'USERS_COUNT'
export const USERS_ONLINE = 'USERS_ONLINE'
export const UPDATE_IMAGE = 'UPDATE_IMAGE'