//QUIZ - QUESTIONS - ANSWERS
export const GET_QUIZ = 'GET_QUIZ';
export const GET_QUIZZES = 'GET_QUIZZES';
export const SAVE_ANSWER = 'SAVE_ANSWER'; 
export const ADD_SCORE = 'ADD_SCORE'; //MOVE TO SCORE
export const TOP_QUIZZES_BY_SUBJECT = 'TOP_QUIZZES_BY_SUBJECT'
export const TOP_QUIZZES_BY_LEVEL = 'TOP_QUIZZES_BY_LEVEL'
export const TOP_QUIZZES_BY_USER = 'TOP_QUIZZES_BY_USER'
export const QUIZZES_COUNT = 'QUIZZES_COUNT'
export const QUIZZES_SUM_PLAYED = 'QUIZZES_SUM_PLAYED'
export const QUESTIONS_COUNT = 'QUESTIONS_COUNT'
export const SUGGEST_QUIZZES = 'SUGGEST_QUIZZES'
export const RESET_CHOICES = 'RESET_CHOICES'
export const GET_QUIZZES_BY_USER = 'GET_QUIZZES_BY_USER'
export const GET_NEW_QUIZZES = 'GET_NEW_QUIZZES'
export const DELETE_QUIZ = 'DELETE_QUIZ'
export const CREATE_QUIZ = 'CREATE_QUIZ'
export const CREATE_QUESTIONS = 'CREATE_QUESTIONS'
export const IMPORT_QUESTION = 'IMPORT_QUESTION'
export const EDIT_QUIZ = 'EDIT_QUIZ'
export const CLOSE_QUIZ = 'CLOSE_QUIZ'

//SUBJECT
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const GET_SUBJECT = 'GET_SUBJECT'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT'
export const COUNT_SUBJECTS = 'COUNT_SUBJECTS'

//LEVEL
export const GET_LEVELS = 'GET_LEVELS';
export const ADD_LEVEL = 'ADD_LEVEL'
export const DELETE_LEVEL = 'DELETE_LEVEL'
export const UPDATE_LEVEL = 'UPDATE_LEVEL'


//SCORE
export const GET_SCORES = 'GET_SCORES'
export const NEW_SCORES = 'NEW_SCORES'
export const FILTER_SCORES = 'FILTER_SCORES'
export const LAST_THREE_WINNERS = 'LAST_THREE_WINNERS'
export const GET_WINNERS = 'GET_WINNERS'
export const GET_WINNERS_BY_QUIZ = 'GET_WINNERS_BY_QUIZ'
export const CHECK_WINNER = 'CHECK_WINNER'

export const TOP_SCHOOLS_BY_SCORE = 'TOP_SCHOOLS_BY_SCORE'
export const TOP_SCHOOLS_BY_MEDALS = 'TOP_SCHOOLS_BY_MEDALS'
export const TOP_SCHOOLS_THIS_WEEK = 'TOP_SCHOOLS_THIS_WEEK'
export const TOP_SCHOOLS_BY_LEVEL = 'TOP_SCHOOLS_BY_LEVEL'
export const TOP_SCHOOLS_BY_SUBJECT = 'TOP_SCHOOLS_BY_SUBJECT'

export const TOP_USERS_BY_SCORE = 'TOP_USERS_BY_SCORE'
export const TOP_USERS_BY_MEDALS = 'TOP_USERS_BY_MEDALS'
export const TOP_USERS_THIS_WEEK = 'TOP_USERS_THIS_WEEK'
export const TOP_USERS_BY_LEVEL = 'TOP_USERS_BY_LEVEL'
export const TOP_USERS_BY_SUBJECT = 'TOP_USERS_BY_SUBJECT'

export const USER_COUNT_SCORE = 'USER_COUNT_SCORE'
export const USER_SUM_SCORE = 'USER_SUM_SCORE'
export const USER_SUM_MEDALS = 'USER_SUM_MEDALS'
export const USER_AVERAGE = 'USER_AVERAGE'
export const USER_FAVORITE = 'USER_FAVORITE'

export const POPULAR_SUBJECTS = 'POPULAR_SUBJECTS'

export const USER_MEDALS_BY_SCHOOL = 'USER_MEDALS_BY_SCHOOL'
export const SCHOOL_SUM_MEDALS = 'SCHOOL_SUM_MEDALS'



//USER
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_USER = 'GET_USER'
export const GET_USERS = 'GET_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const NEWEST_USER = 'NEWEST_USER'
export const USERS_COUNT = 'USERS_COUNT'
export const USERS_ONLINE = 'USERS_ONLINE'
export const UPDATE_IMAGE = 'UPDATE_IMAGE'
export const GET_NEW_MEMBERS = 'GET_NEW_MEMBERS'
export const CHECK_PERMISSION = 'CHECK_PERMISSION'



//SCHOOL
export const GET_SCHOOLS = 'GET_SCHOOLS';
export const GET_SCHOOL = 'GET_SCHOOL'
export const ADD_SCHOOL = 'ADD_SCHOOL'
export const DELETE_SCHOOL = 'DELETE_SCHOOL'
export const UPDATE_SCHOOL = 'UPDATE_SCHOOL'
export const COUNT_SCHOOLS = 'COUNT_SCHOOLS'